org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.suppressUnsupportedCompileSdk=35
android.enableAnnotationProcessorIncremental=true
android.enableAnnotationProcessorParallel=true
