plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.jaowzin.carromloader'
    compileSdk 35

    defaultConfig {
        applicationId 'dev.jaowzin.carromloader'
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName '1.5.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }
}
